### ISSUE TITLE
Some really important feature request for Oneplus 5 (or any mobile).

### ISSUE THREAD

**Issue by PranavBhattarai** [AOSPA/android_kernel_oneplus_msm8998#1]
1. **Advance reboot** option like PE, OOS, etc to toggle from Developer options.
![Screenshot from 2020-08-04 16-24-13](https://user-images.githubusercontent.com/32763112/89284811-0ada1600-d66f-11ea-97df-7f5691b09a9a.png)

2. Display **Selinux status** in either About Phone or System Information like Samsung.
![Screenshot from 2020-08-04 16-24-01](https://user-images.githubusercontent.com/32763112/89284845-175e6e80-d66f-11ea-928b-3196552cad83.png)

3. **Schedule Shutdown** option like in OOS [which helps users to automatically shutdown/restart the device at a specific time.](https://wccftech.com/how-to/how-to-make-your-oneplus-phone-restart-automatically-overnight/)
![image](https://user-images.githubusercontent.com/32763112/89270479-1d4a5480-d65b-11ea-9886-8c74e7e05131.png)

4. Option to hide recent apps in Paranoid launcher 10 like in Pixel Launcher 10. 
![Screenshot from 2020-08-04 16-22-46](https://user-images.githubusercontent.com/32763112/89284650-d49c9680-d66e-11ea-81cf-81bfc8257914.png)

5. Option to **hide battery icon** in the Status bar. And let us enable battery percentage even if we battery icon like in OOS, PE, etc. 
![Screenshot from 2020-08-04 16-20-10](https://user-images.githubusercontent.com/32763112/89284498-9901cc80-d66e-11ea-9a44-ae0f4c36f692.png)

6. **Randomized Mac-address** by default just like in PE10.
![Screenshot from 2020-08-04 16-14-04](https://user-images.githubusercontent.com/32763112/89283836-8fc43000-d66d-11ea-9521-053735d7e64b.png)

**Comment by evan-a-a** [comment]
This is not a forum for feature requests. Please discuss this in our telegram or submit commits to gerrit.
